[files]
bus = "bus_3_bus.csv"
branch = "bus_3_branch.csv"
gen = "bus_3_gen.csv"
switch = "bus_3_switch.csv"
gendata = "bus_3_gendata.csv"
load = "bus_3_load.csv"
loaddata = "bus_3_loaddata.csv"
storage = "bus_3_storage.csv"

[configuration]
baseMVA = 100.0
